import math
def investment_procedure(investment_details):
 a, r, y = investment_details
total = a * math.pow((1 + r / 100), y)
dollar = "dollars"
success = total > 0
return total, dollar, success
def iterate_investment():
 investments = []
 while True:
  a = float(input("Enter Investment Amount: "))
  r = float(input("Enter Interest Rate: "))
  y = float(input("Enter Number of Years: "))
  investment_details = [a, r, y]
  is_valid = all([500 <= a <= 100000, r >= 0, y >= 0])
  if not is_valid:
   print("Invalid Amount")
  else:
   total, dollar, success = investment_procedure(investment_details)
   investments.append((total, dollar, success))
   print(f"The total amount after {y} years is {total} {dollar}, Success: {success}")
  continue_input = input("Do you want to enter another investment? (yes/no): ").lower()
  if continue_input != 'yes':
   break
 return investments
iterate_investment()
